/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package researchproject.Parser;

import java.util.*;  

/**
 *
 * @author HP
 */
public class BsbmQuery {
    private static final  ArrayList queries = new ArrayList();
    
    static  {
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix rev: <http://purl.org/stuff/rev#> Select ?productType (count(?review) As ?reviewCount) { ?productType a bsbm:ProductType . ?product a ?productType . ?product bsbm:producer ?producer . ?producer bsbm:country <http://downlode.org/rdf/iso-3166/countries#US> . ?review bsbm:reviewFor ?product . ?review rev:reviewer ?reviewer . ?reviewer bsbm:country <http://downlode.org/rdf/iso-3166/countries#GB> . } Group By ?productType Order By desc(?reviewCount) ?productType Limit 10");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> SELECT ?otherProduct (count(?otherFeature) As ?sameFeatures) { ?otherProduct a bsbm:Product . ?otherProduct bsbm:productFeature ?otherFeature . <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer5/Product206> bsbm:productFeature ?feature . FILTER(?otherProduct != <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer5/Product206>) FILTER(?feature=?otherFeature) } Group By ?otherProduct Order By desc(?sameFeatures) ?otherProduct Limit 10");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix rev: <http://purl.org/stuff/rev#> prefix dc: <http://purl.org/dc/elements/1.1/> prefix xsd: <http://www.w3.org/2001/XMLSchema#> Select ?product (xsd:float(?monthCount)/?monthBeforeCount As ?ratio) { { Select ?product (count(?review) As ?monthCount) { ?review bsbm:reviewFor ?product . ?review dc:date ?date . Filter(?date >= \"2008-03-01\"^^<http://www.w3.org/2001/XMLSchema#date> && ?date < \"2008-04-01\"^^<http://www.w3.org/2001/XMLSchema#date>) } Group By ?product } { Select ?product (count(?review) As ?monthBeforeCount) { ?review bsbm:reviewFor ?product . ?review dc:date ?date . Filter(?date >= \"2008-02-01\"^^<http://www.w3.org/2001/XMLSchema#date> && ?date < \"2008-03-01\"^^<http://www.w3.org/2001/XMLSchema#date>) # } Group By ?product Having (count(?review)>0) } } Order By desc(xsd:float(?monthCount) / ?monthBeforeCount) ?product Limit 10");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix xsd: <http://www.w3.org/2001/XMLSchema#> Select ?feature ((?sumF*(?countTotal-?countF))/(?countF*(?sumTotal-?sumF)) As ?priceRatio) { { Select (count(?price) As ?countTotal) (sum(xsd:float(str(?price))) As ?sumTotal) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType45> . # ?offer bsbm:product ?product . ?offer bsbm:price ?price . } } { Select ?feature (count(?price2) As ?countF) (sum(xsd:float(str(?price2))) As ?sumF) { ?product2 a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType45> . ?product2 bsbm:productFeature ?feature . ?offer2 bsbm:product ?product2 . ?offer2 bsbm:price ?price2 . } Group By ?feature } } Order By desc(?priceRatio) ?feature Limit 100");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix rev: <http://purl.org/stuff/rev#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> Select ?country ?product ?nrOfReviews ?avgPrice { { Select ?country (max(?nrOfReviews) As ?maxReviews) { { Select ?country ?product (count(?review) As ?nrOfReviews) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType45> . ?review bsbm:reviewFor ?product . ?review rev:reviewer ?reviewer . ?reviewer bsbm:country ?country . } Group By ?country ?product } } Group By ?country } { Select ?product (avg(xsd:float(str(?price))) As ?avgPrice) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType45> . ?offer bsbm:product ?product . ?offer bsbm:price ?price . } Group By ?product } { Select ?country ?product (count(?review) As ?nrOfReviews) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType45> . ?review bsbm:reviewFor ?product . ?review rev:reviewer ?reviewer . ?reviewer bsbm:country ?country . } Group By ?country ?product } FILTER(?nrOfReviews=?maxReviews) } Order By desc(?nrOfReviews) ?country ?product Limit 100");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix rev: <http://purl.org/stuff/rev#> Select ?reviewer (avg(xsd:float(?score)) As ?reviewerAvgScore) { { Select (avg(xsd:float(?score)) As ?avgScore) { ?product bsbm:producer <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer9/Producer9> . ?review bsbm:reviewFor ?product . { ?review bsbm:rating1 ?score . } UNION { ?review bsbm:rating2 ?score . } UNION { ?review bsbm:rating3 ?score . } UNION { ?review bsbm:rating4 ?score . } } } { Select ?reviewer ?score Where { ?product bsbm:producer <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer9/Producer9> . ?review bsbm:reviewFor ?product . ?review rev:reviewer ?reviewer . { ?review bsbm:rating1 ?score . } UNION { ?review bsbm:rating2 ?score . } UNION { ?review bsbm:rating3 ?score . } UNION { ?review bsbm:rating4 ?score . } } } } Group By ?reviewer Having (avg(xsd:float(?score)) > min(?avgScore) * 1.5) LIMIT 100");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix xsd: <http://www.w3.org/2001/XMLSchema#> Select ?product { { Select ?product (count(?offer) As ?offerCount) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType19> . ?offer bsbm:product ?product . ?offer bsbm:vendor ?vendor . ?vendor bsbm:country ?country . FILTER(?country!=<http://downlode.org/rdf/iso-3166/countries#UK>) } Group By ?product Order By desc(?offerCount) } } Limit 1000");
      queries.add("prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> prefix xsd: <http://www.w3.org/2001/XMLSchema#> Select ?vendor (xsd:float(?belowAvg)/?offerCount As ?cheapExpensiveRatio) { { Select ?vendor (count(?offer) As ?belowAvg) { { { Select ?vendor ?product ?price ?offer WHERE { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType19> . ?offer bsbm:product ?product . ?offer bsbm:vendor ?vendor . ?offer bsbm:price ?price . } } { Select ?product (avg(xsd:float(str(?price))) As ?avgPrice) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType19> . ?offer bsbm:product ?product . ?offer bsbm:vendor ?vendor . ?offer bsbm:price ?price . } Group By ?product } } FILTER (xsd:float(str(?price)) < ?avgPrice) } Group By ?vendor } { Select ?vendor (count(?offer) As ?offerCount) { ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType19> . ?offer bsbm:product ?product . ?offer bsbm:vendor ?vendor . } Group By ?vendor } } Order by desc(xsd:float(?belowAvg)/?offerCount) ?vendor limit 10");
    }
    
    
    public static String getQuery(int queryId){
        return queries.get(queryId).toString();
    }
    
    
    
}
